import asyncio
from python_socks.async_.asyncio import Proxy
from python_socks import ProxyType
from models.notification import Notification , NotificationType
import re


## Temporary
class InvalidOnionHost(Exception): pass
class InvalidPort(Exception): pass

class ClientConnection():

    """
        This class represents a active asynchronous connection between a client and a server
        using tor as a proxy.

        The connection run in the same event loop from the controller in a asynchronous task
        stored in the object -server_task-.
        The class keeps the incomming messages and the notifications in itself, to be collected by
        the controller layer during his life cycle.

        Attributes
        ----------

        pin (not implement yet!): str
            Credential used to connect with the server
        HOST : str
            Hostname of the server
        PORT : int
            Server open port for the connection
        proxy_port : int (default = 9050)
            Port to connect to tor proxy
        sock : Proxy.socket.socket
            Socket that defines the connection
        writer : StreamWriter
            Object to send data to the server
        _connected : Bool
            Indicates wether there is a active connecition running
        message_queue : asyncio.Queue
            Asynchronus queue to store the messages incoming from the web
        notification_queue : asyncio.Queue
            Asynchronus Queue to store the notifications generated by the class itself
        server_task : asyncio.Task
            Stores the task responsible to run the asynchronous connection
        
        Methods
        --------

        run()
            Initialize the queues inside the asynchronous event loop context an start the 
            connection process
        close_connection()
            Shuts down the connection asynchronous task and define the state as not connected
        start_connection()
            Configure the proxy, define a socket and starts a asyncion TCP connection
        connection_handler():
        send_message()
            Send a message comming from the controller layer to the connected server
        get_message_in_queue()
            Function called by the controller layer to collect messages comming from the server
        get_notification_in_queue()
            Function called by the controller layer to collect notifications generated by the class
    
    """

    def __init__(self, pin = None):
        self.pin = pin
        self.HOST  = None 
        self.PORT = None
        self.proxy_port = 9050
        self.sock = None
        self.writer = None  
        self._connected = False
        self.messages_queue = asyncio.Queue()
        self.notification_queue= asyncio.Queue()
        self.messages_to_send_queue = asyncio.Queue()
        self.server_task =  asyncio.Task 


    # This fucnitn will be moved for a proper class
    def validate_connection_state(func):
        async def inner_wrapper(self ,*args, **kwargs):
            try:
                if self._connected:
                    return await func(self,*args, **kwargs)
                else:
                    raise ValueError("The connection didnt start yet!")
            except Exception as e:
                raise e
        return inner_wrapper
    
    import re


    def validate_onion_and_port(self ,host: str, port: int):

        host = host.strip().lower()

        if not host.endswith(".onion"):
            raise InvalidOnionHost("Hostname must end with '.onion'.")

        name = host[:-6]  # remove ".onion"

        # v3: 56 chars base32 (a-z2-7)
        if len(name) != 56:
            raise InvalidOnionHost("Invalid Onion name, it must have 56 characters")

        if not re.fullmatch(r"[a-z2-7]+", name):
            raise InvalidOnionHost("Invalid Onion name: it must be base32 [a-z2-7].")

        try:
            port = int(port)
        except (TypeError, ValueError):
            raise InvalidPort("Port number must be an Integer")

        if not (1 <= port <= 65535):
            raise InvalidPort("Invalid interval number for the port (1–65535).")

    
    async def run(self, host: str, port: int ) -> None:

        self.validate_onion_and_port(host, port)

        self.messages_queue = asyncio.Queue()
        self.notification_queue= asyncio.Queue()

        self.HOST = host
        self.PORT = port
        await self.start_connection()
 
    @validate_connection_state
    async def close_connection(self):
        ## NEED TO WORK TO CLOSE WEB CONNECTION
        ## AND GARATEE THE END OF ALL PENDING TASKS
        self._connected = False
        self.server_task.cancel()
        try:
            await self.server_task
        except asyncio.CancelledError :
            pass
        await self.notification_queue.put(Notification(NotificationType.WARNING,
                                          "Connection finished with the server."))
        

    @validate_connection_state
    async def connection_handler(self,reader, writer):
        self.writer = writer
        while self._connected:
            try:
                data = await reader.readuntil(separator=b'\0')
            except asyncio.exceptions.IncompleteReadError as e:
                data = e.partial
                if not data:
                    await self.notification_queue.put(
                        Notification(NotificationType.WARNING, f"Error reading message from server {writer.get_extra_info('peername')}"))
            except:
                await self.notification_queue.put(
                                            Notification(NotificationType.WARNING, f"""Unexpected error from server: {writer.get_extra_info('peername')}
                                                        closing connection..."""))
                break

            if not data:
                await self.notification_queue.put(
                    Notification(NotificationType.WARNING,"Connection closed by the server."))
                break
            
            message = data.decode().strip()
            msg_info = {
                "entry": message,
                "author_name": (writer.get_extra_info('peername')), 
                "owner": False
            }



            await self.messages_queue.put(msg_info)

    async def start_connection(self):

        try:
            self.proxy = Proxy(proxy_type= ProxyType.SOCKS5,
                            host= "127.0.0.1" , port = self.proxy_port, rdns=True)
            self.sock  = await self.proxy.connect(dest_host = self.HOST,dest_port= self.PORT,
            )   
        except TimeoutError as e:
            raise RuntimeError(f"Connection timeout in proxy connection {self.HOST}:{self.PORT}") from e
        except ConnectionError as e:
            raise ConnectionError(f"Error! Unable to connect to proxy {self.HOST}:{self.PORT}") from e
        
        try :
            reader,writer = await asyncio.open_connection( 
                sock = self.sock)
            self._connected = True
        except TimeoutError:
            raise RuntimeError(f"Connection timeout trying to connect to server {self.HOST}:{self.PORT}")
        except ConnectionError as e:
            raise ConnectionError(f"Error! Unable to connect to server {self.HOST}:{self.PORT}") from e
        else:
            # self.messages_checker_task = asyncio.create_task(self.check_messages_for_web())
            self.server_task = asyncio.create_task(self.connection_handler(reader,writer))
        # await self.end_connection()
        
    @validate_connection_state
    async def send_message(self, message):
        data = message["entry"]
        data_encoded = (data + "\n").encode()
        w = self.writer

        w.write(data_encoded)
        try:
            await w.drain()
        except (ConnectionResetError , ConnectionRefusedError) as e: 
            await self.notification_queue.put(
                Notification(NotificationType.WARNING , 
                "Unable to send the message"))
        

    # @validate_connection_state
    async def get_message_in_queue(self):
        msg = await self.messages_queue.get()
        return msg
    
    async def get_notification_in_queue(self):
        return await self.notification_queue.get()
    
    