import asyncio
import re
# from connection.tor_service_manager import TorServiceManager
from src.models import Notification , NotificationType
from typing import Any, Callable
import traceback
from decorators import validate_connection_state


## Temporary

class ServerConnection():

    """
        This class defines a local asynchronous server connected with onion server
        running in the background thread created by the controller layer. 

        It stores the notifications generated by itself and the messages to 
        broadcast to all connections.
        It operates two asynchronous tasks: the server listener and a schedule 
        that verify the breadcast queue to collect new messages to send them all to the 
        users connected to the server
        Parameters
        ----------
        users : list
            (Not implemented yet)
        name : str
            Server connection name
        pin : str
            (Not implemented yet)
        onion_adress : str
            Complete onion server representation
        PORT : int
            Local server port which the onion server connects
        HOST: str
            Defines where the server will listen to, it awaits the local onion process 
            connection by defalu (default = 127.0.0.1)
        my_connecions : list
            Stores all the writers type data from all the clients connected
        _connected : Bool
            Indicates wether there is a active connecition running
        message_queue : asyncio.Queue
            Asynchronus queue to store the messages incoming from the web
        notification_queue : asyncio.Queue
            Asynchronus Queue to store the notifications generated by the class itself
        broadcast_queue : asyncio.Queue
            Asynchronus Queue to store the messages that should be send to all the connected server's 
            clients

        Methods
        -------
        close_server
            Shut down the the asynchronus taks running in the class, close the connection and
            the server
        delet_user (not implemented yet)
        start_server (port : int)
            Start the server state and the class asynchronous queues in the proper event loop context
        server_listener:
            Start the server properly, listening in the local host for the onion connection
        connection_handler:
            Server listener loop receive the data e store in the local message and broadcast queue, 
            treating any error in the process
        check_messages_for_web:
            Asynchronous task to schedule the check for new messages in the broadcast queue
        broadcast_messae(message. w): 
            Send a message for a connected client
        send_message:
            Send a messages from the server itself for all connections
          get_message_in_queue()
            Function called by the controller layer to collect messages comming from the clients
        get_notification_in_queue()
            Function called by the controller layer to collect notifications generated by the class

    """


    def __init__(self, name  ,notification_bus, pin = None):


        self.users = []
        self.name = name
        self.pin = pin

        self.onion_adress = ""
        self.PORT = None
        self.HOST = "127.0.0.1"
        self.my_connections = set()
        self._connected = False
        self.notification_bus = notification_bus
        self.broadcast_queue : asyncio.Queue = None
        self.messages_queue: asyncio.Queue = None
        # self.notification_queue : asyncio.Queue
        # self.server_task : asyncio.Task  
        self.check_messages_for_web_task : asyncio.Task = None
        # self.broadcast_messages_task : asyncio.Task # removed

    ## move this to his own class

    

    #to implement
    def delete_user(self, user_id):
        self.users.remove(user_id)
        self.local_black_list.append()
    
    def initialize(self):
        self.messages_queue = asyncio.Queue()
        # self.notification_queue = asyncio.Queue()
        # self.messages_to_send_queue = asyncio.Queue()
        self.broadcast_queue = asyncio.Queue()

    async def start_server(self ,port):

        self.PORT  = port
        await self.server_listener() 


    @validate_connection_state    
    async def check_messages_for_web(self):

        while self._connected:
            try:
                last_message = await self.broadcast_queue.get()
                # await self.broadcast_message(last_message)
                await asyncio.gather(*[
                    self.broadcast_message(last_message, w) for w in self.my_connections
                ])
            except  asyncio.CancelledError as e :
                raise e
            except Exception as e:
                await self.notification_bus.send(Notification(
                    NotificationType.ERROR,f"FATAL ERROR: {e})"))
                await asyncio.sleep(2)
                ## this is responsibilty from controller
                # asyncio.create_task(self.close_server()) 
                
   
    @validate_connection_state
    async def connection_handler(self,reader, writer):
        ## verify if the same source is connected and then block it
        await self.notification_bus.send(Notification(NotificationType.INFO, f"""New user connected: {writer.get_extra_info('peername')}"""))
        self.my_connections.add(writer)
        while self._connected:
            try:
                data = await reader.readuntil(separator=b'\0')

            except asyncio.exceptions.IncompleteReadError as e:
                data = e.partial
                if not data:
                    await self.notification_bus.send(
                        Notification(NotificationType.WARNING, f"User {writer.get_extra_info('peername')}"))
                    break
            except asyncio.exceptions.LimitOverrunError as e:
                await self.notification_bus.send( Notification(NotificationType.ERROR, 
                    f"Message too large (> than {e.consumed} bytes)"))
                break
            except:
                await self.notification_bus.send(
                                            Notification(NotificationType.WARNING, f"""Unexpected error from user: {writer.get_extra_info('peername')}
                                                            closing connection..."""))
                break
            if not data: ## this block might be unecessary..
                await self.notification_bus.send(
                Notification(NotificationType.WARNING,f"User {writer.get_extra_info('peername')}"))
                break
            try:
                message = data.decode().rstrip('\x00').strip()
                msg_info = {
                    "entry": message,
                    "author_name": writer.get_extra_info('peername'), 
                    "owner": False
                }

            except UnicodeDecodeError as e:
                await self.notification_bus.send(
                    Notification(NotificationType.ERROR, 
                        f"Failed to decode message from {writer.get_extra_info('peername')}: {str(e)}"))
                break
            except ValueError as e:
                await self.notification_bus.send(
                    Notification(NotificationType.ERROR, 
                        f"Invalid message format from {writer.get_extra_info('peername')}: {str(e)}"))
                break
            except Exception as e:
                await self.notification_bus.send(
                    Notification(NotificationType.ERROR, 
                        f"Unexpected error decoding message from {writer.get_extra_info('peername')}: {str(e)}"))
                break
            else:
                await self.messages_queue.put(msg_info)
                await self.broadcast_queue.put(msg_info)

        if writer in self.my_connections: ## If the server  not ends before this
            self.my_connections.remove(writer)


    async def server_listener(self):
   

        try:
            server = await asyncio.start_server(self.connection_handler, self.HOST, 
                                                self.PORT,reuse_address = True)
            sock = server.sockets[0]
            self.server = server
            local_port = sock.getsockname()[1]
            self.onion_adress = f"{self.HOST}:{local_port}"

        except OSError as e:
            raise OSError(f"Failed to start server on {self.HOST}:{self.PORT}") from e
        except Exception as e:
            raise RuntimeError(f"Unexpected error while starting the server") from e
        else:
            await self.notification_bus.send(
            Notification(NotificationType.SUCCESS, f"Server started on {self.HOST}:{local_port}")
            )
        self._connected = True
        self.check_messages_for_web_task = asyncio.create_task(self.check_messages_for_web())
        

    @validate_connection_state            
    async def broadcast_message(self, message , w):


        data = message["entry"].replace("\x00", "")
        data_encoded = (data + "\n\0").encode()

        # for w in self.my_connections:
        peername = w.get_extra_info('peername')

        try: ## this is just a simple version of proper indentificatiion method
            if message["owner"] or message["author_name"][1] != peername[1] :
                w.write(data_encoded)
                await w.drain()
        except (ConnectionResetError , ConnectionRefusedError): 
            await self.notification_bus.send(
                Notification(NotificationType.INFO, f"Error sending message to {peername}"))
        except Exception as e:
            raise e
    
    @validate_connection_state    
    async def send_message(self,message):
        await self.broadcast_queue.put(message)
        

    
    @validate_connection_state    
    async def close_server(self):
        self._connected = False
        try:
            self.check_messages_for_web_task.cancel()
            await self.check_messages_for_web_task
        except asyncio.CancelledError:
            pass

        while self.my_connections:
            try:
                writer = self.my_connections.pop()
                writer.close()
                await writer.wait_closed()
            except:
                pass

        self.server.close()
        await self.server.wait_closed()

    # @validate_connection_state
    async def get_message_in_queue(self):
        return await self.messages_queue.get()
    
    # async def get_notification_in_queue(self):
    #     return await self.notification_queue.get()