import asyncio
import re
# from connection.tor_service_manager import TorServiceManager
from src.models import Notification , NotificationType
from typing import Any, Callable
import traceback
from decorators import validate_connection_state
from infrastructure import server_connection_handshake ,server_success_handshake_response, server_failure_handshake_response
from .base_connection import BaseConnection
from bidict import bidict
from models import ServerMessage


## This will use an interface
class ServerConnection(BaseConnection):

    """
        This class defines a local asynchronous server connected with onion server
        running in the background thread created by the controller layer. 

        It stores the notifications generated by itself and the messages to 
        broadcast to all connections.
        It operates two asynchronous tasks: the server listener and a schedule 
        that verify the breadcast queue to collect new messages to send them all to the 
        users connected to the server
        Parameters
        ----------
        users : list
            (Not implemented yet)
        name : str
            Server connection name
        password : str
            (Not implemented yet)
        onion_adress : str
            Complete onion server representation
        PORT : int
            Local server port which the onion server connects
        HOST: str
            Defines where the server will listen to, it awaits the local onion process 
            connection by defalu (default = 127.0.0.1)
        my_connecions : list
            Stores all the writers type data from all the clients connected
        _connected : Bool
            Indicates wether there is a active connecition running
        message_queue : asyncio.Queue
            Asynchronus queue to store the messages incoming from the web
        notification_queue : asyncio.Queue
            Asynchronus Queue to store the notifications generated by the class itself
        broadcast_queue : asyncio.Queue
            Asynchronus Queue to store the messages that should be send to all the connected server's 
            clients

        Methods
        -------
        close_server
            Shut down the the asynchronus taks running in the class, close the connection and
            the server
        delet_user (not implemented yet)
        start_server (port : int)
            Start the server state and the class asynchronous queues in the proper event loop context
        startup:
            Start the server properly, listening in the local host for the onion connection
        connection_handler:
            Server listener loop receive the data e store in the local message and broadcast queue, 
            treating any error in the process
        check_messages_for_web:
            Asynchronous task to schedule the check for new messages in the broadcast queue
        broadcast_messae(message. w): 
            Send a message for a connected client
        send_message:
            Send a messages from the server itself for all connections
          get_message_in_queue()
            Function called by the controller layer to collect messages comming from the clients

    """


    def __init__(self, name  ,notification_bus):


        self.users = []
        self.name = name
        self.password = None

        self.onion_adress = ""
        self.PORT = None
        self.HOST = "127.0.0.1"
        self.my_connections = bidict()
        self._connected = False
        self.notification_bus = notification_bus
        self.broadcast_queue : asyncio.Queue = None
        self.messages_queue: asyncio.Queue = None
        self.check_messages_for_web_task : asyncio.Task = None

    @validate_connection_state    
    async def send_message(self,message):
        await self.broadcast_queue.put(message)
        

    def initialize(self):
        # self.messages_queue = asyncio.Queue()
        super().initialize()
        # self.notification_queue = asyncio.Queue()
        # self.messages_to_send_queue = asyncio.Queue()
        self.broadcast_queue = asyncio.Queue()

    async def run(self ,port,password):

        self.PORT  = port
        self.password = password
        await self.startup() 


    @validate_connection_state    
    async def check_messages_for_web(self):

        while self._connected:
            try:
                last_message = await self.broadcast_queue.get()
                # await self.broadcast_message(last_message)
                await asyncio.gather(*[
                    self.broadcast_message(last_message, w) for w in self.my_connections
                ])
            ## isso aq lanca uma ecxxcecao quamndo a apçicacao é fechada
            except  asyncio.CancelledError as e :
                raise e
            except Exception as e:
                await self.notify(
                    NotificationType.ERROR,f"FATAL ERROR: {e}")
                await asyncio.sleep(2)
                ## this is responsibilty from controller
                # asyncio.create_task(self.close_server()) 

    async def remove_connection(self, writer):

        try:
            writer.close()
            await writer.wait_closed()
            self.my_connections.pop(writer, None)
        except Exception as e:
            print(e)
            pass

        

    
    async def _handshake(self, reader , writer,password, local_clients):
            
            handshake_data = await asyncio.wait_for(reader.readuntil(separator=b'\0'), timeout=6.0)
            try:

                client_data = await server_connection_handshake(handshake_data, password, local_clients.inverse)
            except Exception as e:

                res = server_failure_handshake_response()
                writer.write(res)
                await writer.drain()
                raise ConnectionRefusedError
            else:
                res = server_success_handshake_response(self.name)
                writer.write(res)
                await writer.drain()
                return client_data
   
    @validate_connection_state
    async def connection_handler(self,reader, writer):

        actual_task = asyncio.current_task()
        actual_task.add_done_callback(self.handle_tasks_errors)
        try:
            client_data = await self._handshake(reader , writer, self.password, self.my_connections)
        except Exception as e:

            await self.notify(NotificationType.INFO, f"""handshake failed""")
            await self.remove_connection(writer)
            return 
        else:
            await self.notify(NotificationType.INFO, f"""New user connected: {writer.get_extra_info('peername')}""")
            self.my_connections[writer] = client_data["name"]
        
        while self._connected:

            try:
                data = await reader.readuntil(separator=b'\0')

            except asyncio.exceptions.IncompleteReadError as e:
                ##loog here
                break

            except asyncio.exceptions.LimitOverrunError as e:
               
               ## logg here
                print("entrou no limitoverrun")
                break

            except Exception as e: 
                await self.notify( NotificationType.WARNING, f"""Unexpected error from user: {writer.get_extra_info('peername')}
                                                            closing connection...""")
                # raise e
                break
         
            try:
                message = data.decode().rstrip('\x00').strip()
                msg_info = {
                    "entry": message,
                    "author_name": self.my_connections[writer], 
                    "owner": False
                }
                print(msg_info)

            except UnicodeDecodeError as e:
                await self.notify(
                    NotificationType.ERROR, 
                        f"Failed to decode message from {writer.get_extra_info('peername')}: {str(e)}")
                break
            except ValueError as e:
                await self.notify(
                    NotificationType.ERROR, 
                        f"Invalid message format from {writer.get_extra_info('peername')}: {str(e)}")
                break
            except Exception as e:
                await self.notify(
                    NotificationType.ERROR, 
                        f"Unexpected error decoding message from {writer.get_extra_info('peername')}: {str(e)}")
                break
            else:
                await self.messages_queue.put(msg_info)
                await self.broadcast_queue.put(msg_info)

        if writer in self.my_connections: ## If the server  not ends before this
            await self.remove_connection(writer)


    async def startup(self):
   

        try:
            server = await asyncio.start_server(self.connection_handler, self.HOST, 
                                                self.PORT,reuse_address = True,limit = 1024)
            sock = server.sockets[0]
            self.server = server
            local_port = sock.getsockname()[1]
            self.onion_adress = f"{self.HOST}:{local_port}"

        except OSError as e:
            raise OSError(f"Failed to start server on {self.HOST}:{self.PORT}") from e
        except Exception as e:
            raise RuntimeError(f"Unexpected error while starting the server") from e
        else:
            await self.notify(
            NotificationType.SUCCESS, f"Server started on {self.HOST}:{local_port}")
            
        self._connected = True
        self.check_messages_for_web_task = asyncio.create_task(self.check_messages_for_web())
        self.check_messages_for_web_task.add_done_callback(self.handle_tasks_errors)
        

    @validate_connection_state            
    async def broadcast_message(self, message , w):


        data = message["entry"].replace("\x00", "")
        # data_encoded = (data + "\0").encode()

        formated_message = ServerMessage(message= data ,author= message["author_name"] ,from_server= message["owner"])
        data_encoded = formated_message.convert_to_stream()
        # for w in self.my_connections:
        author_name = message["author_name"]
        writer_name = self.my_connections[w]

        try: ## this is just a simple version of proper indentificatiion method
            if message["owner"] or author_name != writer_name :
                w.write(data_encoded)
                await w.drain()
        except (ConnectionResetError , ConnectionRefusedError): 
            await self.notify(
                NotificationType.INFO, f"Error sending message to {writer_name}")
        except Exception:
            # raise e
            # logg here
            pass
    

    
    @validate_connection_state    
    async def close_server(self):
        self._connected = False
        try:
            self.check_messages_for_web_task.cancel()
            await self.check_messages_for_web_task
        except asyncio.CancelledError:
            pass

        async def close_connection(writer):
            try:
                writer.close()
                await writer.wait_closed()
            except Exception:
                pass

        if self.my_connections:
            writer_tasks = [close_connection(w) for w in self.my_connections]
            await asyncio.gather(*writer_tasks, return_exceptions=True)
            self.my_connections.clear()
        try:
            self.server.close()
            await self.server.wait_closed()
        except Exception:
            pass

    # # @validate_connection_state
    # async def get_message_in_queue(self):
    #     return await self.messages_queue.get()
    